function Create-7zip([String] $aDirectory, [String] $aZipfile){
  [string]$pathToZipExe = "$($Env:ProgramFiles)\7-Zip\7z.exe";
  [Array]$arguments = "a", "-tzip", "$aZipfile", "$aDirectory", "-r";
  & $pathToZipExe $arguments;
}

# Git details
$gitBranch = (git rev-parse --abbrev-ref HEAD)
$gitCommit = (git rev-parse HEAD).Substring(0, 10)
$buildDate = Get-Date -Format 'yyyy/MM/dd HH:mm:ss'

$fileContent = "
// this file is automatically generated by build script
export const GitVersion = {
  revision: '$gitCommit',
  branch: '$gitBranch',
  buildDate: '$buildDate'
};
"
Write-Output $fileContent | Out-File 'src/environments/versions.ts' -Encoding ascii

# Build
ng build --prod --base-href /admin/ --deployUrl /admin/

# Create archive
$archive = ".\dist\CubesManagement.zip"
if (test-path $archive) { Remove-Item $archive -Force }
Start-Sleep -s 2
Create-7zip .\dist\core-webapp\* .\dist\CubesManagement.zip
# Compress-Archive -Path .\dist\core-webapp\* -DestinationPath .\dist\CubesManagement.zip
